from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .cicd_jobs import _build_core_jobs, _build_merge_conditions, _validate_workspace
from .cicd_models import SAFETY_NOTES, SUPPORTED_FORMATS

__all__ = [
    "generate_github_actions",
    "generate_gitlab_ci",
    "generate_generic",
    "generate_pipeline",
    "render_pipeline_json",
    "render_pipeline_yaml",
    "render_pipeline_text",
]


def _generate_github_actions_yaml(
    jobs: list,
    feature_slug: str | None = None,
) -> str:
    job_parts: list[str] = []
    for job in jobs:
        run_lines = []
        for step_cmd in job.steps:
            run_lines.append(f"        run: {step_cmd}")
        run_block = "\n".join(run_lines)

        job_yaml = (
            f"  {job.name}:\n"
            f"    runs-on: ubuntu-latest\n"
            f"    steps:\n"
            f"      - uses: actions/checkout@v4\n"
            f"      - uses: actions/setup-python@v5\n"
            f"        with:\n"
            f'          python-version: "3.12"\n'
            f"      - name: {job.description or job.name}\n"
            f"{run_block}\n"
        )
        job_parts.append(job_yaml)

    jobs_block = "\n".join(job_parts)

    feature_label = f" (feature: {feature_slug})" if feature_slug else ""

    return (
        f"# SpecSpine CI/CD pipeline{feature_label}\n"
        f"# Generated by specspine cicd generate\n"
        f"# Review before committing\n"
        f"\n"
        f"name: SpecSpine Pipeline\n"
        f"\n"
        f"on:\n"
        f"  push:\n"
        f"    branches: [main]\n"
        f"  pull_request:\n"
        f"    branches: [main]\n"
        f"\n"
        f"permissions:\n"
        f"  contents: read\n"
        f"\n"
        f"jobs:\n"
        f"{jobs_block}"
    )


def _generate_gitlab_ci_yaml(
    jobs: list,
    feature_slug: str | None = None,
) -> str:
    stage_names = [job.name for job in jobs]
    stages_block = "\n".join(f"  - {name}" for name in stage_names)

    job_parts: list[str] = []
    for job in jobs:
        steps_block = "\n".join(f"    - {step_cmd}" for step_cmd in job.steps)

        job_yaml = (
            f"{job.name}:\n"
            f"  stage: {job.name}\n"
            f"  image: python:3.12\n"
            f"  script:\n"
            f"{steps_block}"
        )
        job_parts.append(job_yaml)

    jobs_block = "\n\n".join(job_parts)

    feature_label = f" (feature: {feature_slug})" if feature_slug else ""

    return (
        f"# SpecSpine CI/CD pipeline{feature_label}\n"
        f"# Generated by specspine cicd generate\n"
        f"# Review before committing\n"
        f"\n"
        f"stages:\n"
        f"{stages_block}\n"
        f"\n"
        f"{jobs_block}\n"
    )


def _generate_generic_shell(
    jobs: list,
    feature_slug: str | None = None,
) -> str:
    feature_label = f" (feature: {feature_slug})" if feature_slug else ""

    lines = [
        "#!/usr/bin/env bash",
        "# SpecSpine CI/CD pipeline" + feature_label,
        "# Generated by specspine cicd generate",
        "# Review before committing",
        "",
        "set -euo pipefail",
        "",
        'echo "=== SpecSpine CI/CD Pipeline ==="',
        'echo "Started at $(date -u +%Y-%m-%dT%H:%M:%SZ)"',
        "",
    ]

    for idx, job in enumerate(jobs, 1):
        lines.append(f"# Stage {idx}: {job.name}")
        lines.append(f'echo "--- {job.name}: {job.description or job.name} ---"')
        for step_cmd in job.steps:
            lines.append(f'echo "Running: {step_cmd}"')
            lines.append(f"{step_cmd}")
        lines.append(f'echo "--- {job.name}: passed ---"')
        lines.append("")

    lines.extend([
        'echo "=== All pipeline stages passed ==="',
        'echo "Completed at $(date -u +%Y-%m-%dT%H:%M:%SZ)"',
        "",
    ])

    return "\n".join(lines)


def generate_github_actions(
    root: Path,
    feature_slug: str | None = None,
) -> str:
    jobs = _build_core_jobs(feature_slug)
    return _generate_github_actions_yaml(jobs, feature_slug)


def generate_gitlab_ci(
    root: Path,
    feature_slug: str | None = None,
) -> str:
    jobs = _build_core_jobs(feature_slug)
    return _generate_gitlab_ci_yaml(jobs, feature_slug)


def generate_generic(
    root: Path,
    feature_slug: str | None = None,
) -> str:
    jobs = _build_core_jobs(feature_slug)
    return _generate_generic_shell(jobs, feature_slug)


_GENERATORS = {
    "github-actions": generate_github_actions,
    "gitlab-ci": generate_gitlab_ci,
    "generic": generate_generic,
}


def generate_pipeline(
    root: Path,
    format: str = "github-actions",
    feature_slug: str | None = None,
) -> dict[str, Any]:
    if format not in SUPPORTED_FORMATS:
        raise ValueError(
            f"Unsupported pipeline format: {format}. "
            f"Supported formats: {', '.join(SUPPORTED_FORMATS)}."
        )

    resolved_root = root.expanduser().resolve()
    valid, missing = _validate_workspace(resolved_root)
    if not valid:
        raise FileNotFoundError(
            f"No SpecSpine workspace found at {resolved_root}. "
            f"Missing: {', '.join(missing)}"
        )

    generator = _GENERATORS[format]
    raw_content = generator(resolved_root, feature_slug)

    jobs = _build_core_jobs(feature_slug)
    merge_conditions = _build_merge_conditions(feature_slug)

    return {
        "pipeline_type": format,
        "jobs": tuple(jobs),
        "merge_conditions": tuple(merge_conditions),
        "safety_notes": SAFETY_NOTES,
        "feature_slug": feature_slug,
        "raw_content": raw_content,
    }


def render_pipeline_json(result: dict[str, Any]) -> str:
    serializable: dict[str, object] = {
        "feature_slug": result.get("feature_slug"),
        "jobs": [
            {
                "description": job["description"] if isinstance(job, dict) else job.description,
                "name": job["name"] if isinstance(job, dict) else job.name,
                "steps": list(job["steps"] if isinstance(job, dict) else job.steps),
            }
            for job in result["jobs"]
        ],
        "merge_conditions": [
            {
                "id": mc["id"] if isinstance(mc, dict) else mc.id,
                "required": mc["required"] if isinstance(mc, dict) else mc.required,
                "text": mc["text"] if isinstance(mc, dict) else mc.text,
            }
            for mc in result["merge_conditions"]
        ],
        "pipeline_type": result["pipeline_type"],
        "raw_content": result["raw_content"],
        "safety_notes": list(result["safety_notes"]),
    }
    return json.dumps(serializable, indent=2, sort_keys=True) + "\n"


def render_pipeline_yaml(result: dict[str, Any]) -> str:
    raw = result.get("raw_content", "")
    if raw:
        return raw
    return "# No raw content available; use render_pipeline_json instead.\n"


def render_pipeline_text(result: dict[str, Any]) -> str:
    lines = [
        f"SpecSpine CI/CD Pipeline ({result['pipeline_type']})",
        "",
    ]

    if result.get("feature_slug"):
        lines.append(f"Feature: {result['feature_slug']}")
        lines.append("")

    lines.append("Jobs:")
    for job in result["jobs"]:
        name = job["name"] if isinstance(job, dict) else job.name
        steps = job["steps"] if isinstance(job, dict) else job.steps
        desc = (
            job["description"]
            if isinstance(job, dict) and job.get("description")
            else (job.description if not isinstance(job, dict) else "")
        )
        lines.append(f"  {name}")
        if desc:
            lines.append(f"    Description: {desc}")
        for step in steps:
            lines.append(f"    - {step}")
        lines.append("")

    lines.append("Merge Conditions:")
    for mc in result["merge_conditions"]:
        req = mc["required"] if isinstance(mc, dict) else mc.required
        text = mc["text"] if isinstance(mc, dict) else mc.text
        marker = "[REQUIRED]" if req else "[OPTIONAL]"
        lines.append(f"  {marker} {text}")
    lines.append("")

    lines.append("Safety Notes:")
    for note in result["safety_notes"]:
        lines.append(f"  - {note}")
    lines.append("")

    return "\n".join(lines)
