from __future__ import annotations

__all__ = [
    "_generate_gitlab_ci_yaml",
]


def _generate_gitlab_ci_yaml(
    jobs: list,
    feature_slug: str | None = None,
) -> str:
    stage_names = [job.name for job in jobs]
    stages_block = "\n".join(f"  - {name}" for name in stage_names)

    job_parts: list[str] = []
    for job in jobs:
        steps_block = "\n".join(f"    - {step_cmd}" for step_cmd in job.steps)

        job_yaml = (
            f"{job.name}:\n"
            f"  stage: {job.name}\n"
            f"  image: python:3.12\n"
            f"  script:\n"
            f"{steps_block}"
        )
        job_parts.append(job_yaml)

    jobs_block = "\n\n".join(job_parts)

    feature_label = f" (feature: {feature_slug})" if feature_slug else ""

    return (
        f"# SpecSpine CI/CD pipeline{feature_label}\n"
        f"# Generated by specspine cicd generate\n"
        f"# Review before committing\n"
        f"\n"
        f"stages:\n"
        f"{stages_block}\n"
        f"\n"
        f"{jobs_block}\n"
    )
