from __future__ import annotations

__all__ = [
    "_generate_github_actions_yaml",
]


def _generate_github_actions_yaml(
    jobs: list,
    feature_slug: str | None = None,
) -> str:
    job_parts: list[str] = []
    for job in jobs:
        run_lines = []
        for step_cmd in job.steps:
            run_lines.append(f"        run: {step_cmd}")
        run_block = "\n".join(run_lines)

        job_yaml = (
            f"  {job.name}:\n"
            f"    runs-on: ubuntu-latest\n"
            f"    steps:\n"
            f"      - uses: actions/checkout@v4\n"
            f"      - uses: actions/setup-python@v5\n"
            f"        with:\n"
            f'          python-version: "3.12"\n'
            f"      - name: {job.description or job.name}\n"
            f"{run_block}\n"
        )
        job_parts.append(job_yaml)

    jobs_block = "\n".join(job_parts)

    feature_label = f" (feature: {feature_slug})" if feature_slug else ""

    return (
        f"# SpecSpine CI/CD pipeline{feature_label}\n"
        f"# Generated by specspine cicd generate\n"
        f"# Review before committing\n"
        f"\n"
        f"name: SpecSpine Pipeline\n"
        f"\n"
        f"on:\n"
        f"  push:\n"
        f"    branches: [main]\n"
        f"  pull_request:\n"
        f"    branches: [main]\n"
        f"\n"
        f"permissions:\n"
        f"  contents: read\n"
        f"\n"
        f"jobs:\n"
        f"{jobs_block}"
    )
