from __future__ import annotations

from .cicd_jobs import _build_core_jobs, _build_merge_conditions, _validate_workspace
from .cicd_models import SAFETY_NOTES, SUPPORTED_FORMATS

__all__ = [
    "_generate_github_actions_yaml",
    "_generate_gitlab_ci_yaml",
    "_generate_generic_shell",
]


def _generate_github_actions_yaml(
    jobs: list,
    feature_slug: str | None = None,
) -> str:
    job_parts: list[str] = []
    for job in jobs:
        run_lines = []
        for step_cmd in job.steps:
            run_lines.append(f"        run: {step_cmd}")
        run_block = "\n".join(run_lines)

        job_yaml = (
            f"  {job.name}:\n"
            f"    runs-on: ubuntu-latest\n"
            f"    steps:\n"
            f"      - uses: actions/checkout@v4\n"
            f"      - uses: actions/setup-python@v5\n"
            f"        with:\n"
            f'          python-version: "3.12"\n'
            f"      - name: {job.description or job.name}\n"
            f"{run_block}\n"
        )
        job_parts.append(job_yaml)

    jobs_block = "\n".join(job_parts)

    feature_label = f" (feature: {feature_slug})" if feature_slug else ""

    return (
        f"# SpecSpine CI/CD pipeline{feature_label}\n"
        f"# Generated by specspine cicd generate\n"
        f"# Review before committing\n"
        f"\n"
        f"name: SpecSpine Pipeline\n"
        f"\n"
        f"on:\n"
        f"  push:\n"
        f"    branches: [main]\n"
        f"  pull_request:\n"
        f"    branches: [main]\n"
        f"\n"
        f"permissions:\n"
        f"  contents: read\n"
        f"\n"
        f"jobs:\n"
        f"{jobs_block}"
    )


def _generate_gitlab_ci_yaml(
    jobs: list,
    feature_slug: str | None = None,
) -> str:
    stage_names = [job.name for job in jobs]
    stages_block = "\n".join(f"  - {name}" for name in stage_names)

    job_parts: list[str] = []
    for job in jobs:
        steps_block = "\n".join(f"    - {step_cmd}" for step_cmd in job.steps)

        job_yaml = (
            f"{job.name}:\n"
            f"  stage: {job.name}\n"
            f"  image: python:3.12\n"
            f"  script:\n"
            f"{steps_block}"
        )
        job_parts.append(job_yaml)

    jobs_block = "\n\n".join(job_parts)

    feature_label = f" (feature: {feature_slug})" if feature_slug else ""

    return (
        f"# SpecSpine CI/CD pipeline{feature_label}\n"
        f"# Generated by specspine cicd generate\n"
        f"# Review before committing\n"
        f"\n"
        f"stages:\n"
        f"{stages_block}\n"
        f"\n"
        f"{jobs_block}\n"
    )


def _generate_generic_shell(
    jobs: list,
    feature_slug: str | None = None,
) -> str:
    feature_label = f" (feature: {feature_slug})" if feature_slug else ""

    lines = [
        "#!/usr/bin/env bash",
        "# SpecSpine CI/CD pipeline" + feature_label,
        "# Generated by specspine cicd generate",
        "# Review before committing",
        "",
        "set -euo pipefail",
        "",
        'echo "=== SpecSpine CI/CD Pipeline ==="',
        'echo "Started at $(date -u +%Y-%m-%dT%H:%M:%SZ)"',
        "",
    ]

    for idx, job in enumerate(jobs, 1):
        lines.append(f"# Stage {idx}: {job.name}")
        lines.append(f'echo "--- {job.name}: {job.description or job.name} ---"')
        for step_cmd in job.steps:
            lines.append(f'echo "Running: {step_cmd}"')
            lines.append(f"{step_cmd}")
        lines.append(f'echo "--- {job.name}: passed ---"')
        lines.append("")

    lines.extend([
        'echo "=== All pipeline stages passed ==="',
        'echo "Completed at $(date -u +%Y-%m-%dT%H:%M:%SZ)"',
        "",
    ])

    return "\n".join(lines)
