from __future__ import annotations

__all__ = [
    "_generate_generic_shell",
]


def _generate_generic_shell(
    jobs: list,
    feature_slug: str | None = None,
) -> str:
    feature_label = f" (feature: {feature_slug})" if feature_slug else ""

    lines = [
        "#!/usr/bin/env bash",
        "# SpecSpine CI/CD pipeline" + feature_label,
        "# Generated by specspine cicd generate",
        "# Review before committing",
        "",
        "set -euo pipefail",
        "",
        'echo "=== SpecSpine CI/CD Pipeline ==="',
        'echo "Started at $(date -u +%Y-%m-%dT%H:%M:%SZ)"',
        "",
    ]

    for idx, job in enumerate(jobs, 1):
        lines.append(f"# Stage {idx}: {job.name}")
        lines.append(f'echo "--- {job.name}: {job.description or job.name} ---"')
        for step_cmd in job.steps:
            lines.append(f'echo "Running: {step_cmd}"')
            lines.append(f"{step_cmd}")
        lines.append(f'echo "--- {job.name}: passed ---"')
        lines.append("")

    lines.extend([
        'echo "=== All pipeline stages passed ==="',
        'echo "Completed at $(date -u +%Y-%m-%dT%H:%M:%SZ)"',
        "",
    ])

    return "\n".join(lines)
