from __future__ import annotations

from .feature_bundle_models import *  # noqa: F401,F403
from .feature_bundle_parsers import *  # noqa: F401,F403
from .feature_bundle_io import *  # noqa: F401,F403
from .feature_bundle_validation import *  # noqa: F401,F403
from .feature_bundle_markdown import *  # noqa: F401,F403
from .feature_bundle_render import *  # noqa: F401,F403

__all__ = [
    # models
    "FEATURE_SLUG_RE",
    "FEATURE_FILE_PATHS",
    "FEATURE_STATUSES",
    "FEATURE_PRIORITIES",
    "FEATURE_TRANSITIONS",
    "FEATURE_DIRECTORIES",
    "CHECKBOX_TASK_RE",
    "AC_ID_RE",
    "InvalidFeatureSlug",
    "InvalidFeatureStatus",
    "FeatureBundleExistsError",
    "FeatureBundleNotFoundError",
    "FeatureSyncPlanArtifactExistsError",
    "FeatureStatusTransitionError",
    "FeatureMetadata",
    "FeatureTask",
    "FeatureTraceChecklistItem",
    "FeatureTraceTestPlanItem",
    "FeatureAcceptanceTestCase",
    "FeatureTestCoverageLink",
    "FeatureTraceReport",
    "FeatureReadyCheck",
    "FeatureReadyReport",
    "FeatureTasksReport",
    "FeatureTaskIssueDraft",
    "FeatureTaskIssuesReport",
    "FeatureHandoffReport",
    "FeatureTestsReport",
    "FeatureSyncPlanCommand",
    "FeatureSyncPlan",
    "FeatureSyncPlanArtifacts",
    "IssueDraft",
    "PullRequestDraft",
    "FeatureStatusReport",
    # parsers
    "parse_acceptance_criteria",
    "parse_feature_tasks",
    "parse_quality_checks",
    "parse_test_coverage",
    "parse_test_plan",
    "parse_release_readiness",
    # io
    "_feature_why",
    "build_feature_files",
    "feature_bundle_paths",
    "create_feature_bundle",
    "get_feature_status",
    "list_feature_bundles",
    "read_feature_metadata",
    "get_feature_files",
    "_relative_feature_paths",
    "_transition_payload",
    "_trace_gap",
    "_path_as_posix",
    "_sync_body_source",
    "build_proposal_files",
    "create_proposal_bundle",
    # validation
    "validate_feature_slug",
    "validate_feature_status",
    "normalize_feature_priority",
    "normalize_feature_owner",
    "normalize_feature_assignment",
    "normalize_feature_effort",
    "feature_title",
    # markdown
    "_extract_markdown_section",
    "_extract_markdown_section_lines",
    "_first_line_h1",
    "_markdown_heading",
    # render
    "_extract_scalar",
    "_first_scalar",
    "_section_placeholder",
    "_section_or_placeholder",
    "_why_or_placeholder",
    "_render_metadata_lines",
    "_empty_trace_summary",
    "_feature_sources_from_status",
]
