from __future__ import annotations

from .proposer_ui_nouns_controls import TARGET_NOUNS_CONTROLS
from .proposer_ui_nouns_layouts import TARGET_NOUNS_LAYOUTS
from .proposer_ui_nouns_patterns import TARGET_NOUNS_PATTERNS

__all__ = [
    "TARGET_NOUNS_UI",
]

TARGET_NOUNS_UI = (
    "feature",
    "toggle",
    "mode",
    "button",
    "page",
    "panel",
    "dialog",
    "modal",
    "menu",
    "sidebar",
    "header",
    "footer",
    "toolbar",
    "form",
    "input",
    "field",
    "dropdown",
    "select",
    "checkbox",
    "radio",
    "tab",
    "card",
    "list",
    "table",
    "chart",
    "graph",
    "widget",
    "component",
    "theme",
    "layout",
    "template",
    "style",
    "animation",
    "transition",
    "routing",
    "navigation",
    "search",
    "filter",
    "sort",
    "pagination",
    "validation",
    "notification",
    "alert",
    "toast",
    "banner",
    "badge",
    "tooltip",
    "popover",
    "accordion",
    "carousel",
    "slider",
    "progress",
    "spinner",
    "loader",
    "skeleton",
    "notification",
    "realtime",
    "websocket",
    "sse",
    "polling",
    "subscription",
    "preference",
)
