from __future__ import annotations

__all__ = [
    "IRREGULAR_VERBS",
]

IRREGULAR_VERBS = {
    "add": {"base": "add", "gerund": "adding", "past": "added"},
    "create": {"base": "create", "gerund": "creating", "past": "created"},
    "implement": {"base": "implement", "gerund": "implementing", "past": "implemented"},
    "build": {"base": "build", "gerund": "building", "past": "built"},
    "enable": {"base": "enable", "gerund": "enabling", "past": "enabled"},
    "support": {"base": "support", "gerund": "supporting", "past": "supported"},
    "integrate": {"base": "integrate", "gerund": "integrating", "past": "integrated"},
    "introduce": {"base": "introduce", "gerund": "introducing", "past": "introduced"},
    "develop": {"base": "develop", "gerund": "developing", "past": "developed"},
    "design": {"base": "design", "gerund": "designing", "past": "designed"},
    "extend": {"base": "extend", "gerund": "extending", "past": "extended"},
    "provide": {"base": "provide", "gerund": "providing", "past": "provided"},
    "generate": {"base": "generate", "gerund": "generating", "past": "generated"},
    "configure": {"base": "configure", "gerund": "configuring", "past": "configured"},
    "display": {"base": "display", "gerund": "displaying", "past": "displayed"},
    "show": {"base": "show", "gerund": "showing", "past": "showed"},
    "hide": {"base": "hide", "gerund": "hiding", "past": "hid"},
    "remove": {"base": "remove", "gerund": "removing", "past": "removed"},
    "delete": {"base": "delete", "gerund": "deleting", "past": "deleted"},
    "update": {"base": "update", "gerund": "updating", "past": "updated"},
    "modify": {"base": "modify", "gerund": "modifying", "past": "modified"},
    "change": {"base": "change", "gerund": "changing", "past": "changed"},
    "allow": {"base": "allow", "gerund": "allowing", "past": "allowed"},
    "permit": {"base": "permit", "gerund": "permitting", "past": "permitted"},
    "restrict": {"base": "restrict", "gerund": "restricting", "past": "restricted"},
    "block": {"base": "block", "gerund": "blocking", "past": "blocked"},
    "track": {"base": "track", "gerund": "tracking", "past": "tracked"},
    "monitor": {"base": "monitor", "gerund": "monitoring", "past": "monitored"},
    "validate": {"base": "validate", "gerund": "validating", "past": "validated"},
    "verify": {"base": "verify", "gerund": "verifying", "past": "verified"},
    "test": {"base": "test", "gerund": "testing", "past": "tested"},
    "document": {"base": "document", "gerund": "documenting", "past": "documented"},
    "migrate": {"base": "migrate", "gerund": "migrating", "past": "migrated"},
    "convert": {"base": "convert", "gerund": "converting", "past": "converted"},
    "import": {"base": "import", "gerund": "importing", "past": "imported"},
    "export": {"base": "export", "gerund": "exporting", "past": "exported"},
    "publish": {"base": "publish", "gerund": "publishing", "past": "published"},
    "deploy": {"base": "deploy", "gerund": "deploying", "past": "deployed"},
    "render": {"base": "render", "gerund": "rendering", "past": "rendered"},
    "animate": {"base": "animate", "gerund": "animating", "past": "animated"},
    "sync": {"base": "sync", "gerund": "syncing", "past": "synced"},
}
