from __future__ import annotations

import re

ACTION_VERBS = (
    "add",
    "create",
    "implement",
    "build",
    "support",
    "enable",
    "integrate",
    "introduce",
    "develop",
    "design",
    "extend",
    "provide",
    "generate",
    "configure",
    "display",
    "show",
    "hide",
    "remove",
    "delete",
    "update",
    "modify",
    "change",
    "allow",
    "permit",
    "restrict",
    "block",
    "track",
    "monitor",
    "validate",
    "verify",
    "test",
    "document",
    "migrate",
    "convert",
    "import",
    "export",
    "publish",
    "deploy",
    "render",
    "animate",
    "sync",
)

TARGET_NOUNS = (
    "feature",
    "toggle",
    "mode",
    "button",
    "page",
    "panel",
    "dialog",
    "modal",
    "menu",
    "sidebar",
    "header",
    "footer",
    "toolbar",
    "form",
    "input",
    "field",
    "dropdown",
    "select",
    "checkbox",
    "radio",
    "tab",
    "card",
    "list",
    "table",
    "chart",
    "graph",
    "widget",
    "component",
    "module",
    "service",
    "api",
    "endpoint",
    "handler",
    "middleware",
    "plugin",
    "extension",
    "adapter",
    "connector",
    "integration",
    "pipeline",
    "workflow",
    "report",
    "dashboard",
    "notification",
    "alert",
    "toast",
    "banner",
    "badge",
    "tooltip",
    "popover",
    "accordion",
    "carousel",
    "slider",
    "progress",
    "spinner",
    "loader",
    "skeleton",
    "theme",
    "layout",
    "template",
    "style",
    "animation",
    "transition",
    "routing",
    "navigation",
    "search",
    "filter",
    "sort",
    "pagination",
    "validation",
    "authentication",
    "authorization",
    "permission",
    "role",
    "setting",
    "config",
    "preference",
    "profile",
    "account",
    "session",
    "cache",
    "store",
    "database",
    "model",
    "schema",
    "migration",
    "seed",
    "fixture",
    "mock",
    "stub",
    "test",
    "spec",
    "doc",
    "documentation",
    "readme",
    "changelog",
    "version",
    "release",
    "build",
    "deploy",
    "ci",
    "cd",
    "pipeline",
    "hook",
    "trigger",
    "event",
    "listener",
    "subscriber",
    "publisher",
    "broker",
    "queue",
    "stream",
    "log",
    "logging",
    "metric",
    "monitor",
    "health",
    "status",
    "check",
    "gate",
    "policy",
    "rule",
    "constraint",
    "limit",
    "quota",
    "rate",
    "throttle",
    "retry",
    "timeout",
    "circuit",
    "breaker",
    "fallback",
    "default",
    "gateway",
    "payment",
    "tenant",
    "user",
    "group",
    "organization",
    "team",
    "project",
    "workspace",
    "environment",
    "server",
    "client",
    "proxy",
    "loadbalancer",
    "storage",
    "bucket",
    "container",
    "volume",
    "network",
    "firewall",
    "certificate",
    "token",
    "key",
    "secret",
    "password",
    "email",
    "message",
    "sms",
    "webhook",
    "callback",
    "response",
    "request",
    "header",
    "body",
    "payload",
    "file",
    "attachment",
    "image",
    "video",
    "audio",
    "document",
    "spreadsheet",
    "presentation",
    "archive",
    "backup",
    "snapshot",
    "restore",
    "import",
    "export",
    "sync",
    "notification",
    "realtime",
    "websocket",
    "sse",
    "polling",
    "subscription",
    "preference",
    "configuration",
    "registry",
    "catalog",
    "directory",
    "index",
    "lookup",
    "reference",
    "mapping",
    "translation",
    "localization",
    "internationalization",
)

MODIFIER_PREPOSITIONS = (
    "with",
    "when",
    "if",
    "for",
    "to",
    "where",
    "while",
    "unless",
    "after",
    "before",
    "during",
    "without",
    "by",
    "via",
    "through",
    "on",
    "in",
    "at",
    "from",
    "between",
    "among",
)

COMPONENT_SPLITTERS = re.compile(r"\band\b|\bwith\b|\bplus\b|;")

STOP_WORDS = frozenset({
    "a", "an", "the", "is", "are", "was", "were", "be", "been", "being",
    "have", "has", "had", "do", "does", "did", "will", "would", "could",
    "should", "may", "might", "shall", "can", "need", "must",
    "i", "you", "he", "she", "it", "we", "they",
    "me", "him", "her", "us", "them",
    "my", "your", "his", "its", "our", "their",
    "mine", "yours", "hers", "ours", "theirs",
    "myself", "yourself", "himself", "herself", "itself", "ourselves", "themselves",
    "this", "that", "these", "those",
    "what", "which", "who", "whom", "whose",
    "and", "but", "or", "nor", "for", "yet", "so",
    "if", "then", "than", "else",
    "because", "as", "until", "while", "when", "where", "why", "how",
    "all", "each", "every", "both", "few", "many", "much", "some", "any",
    "no", "not", "only", "own", "same", "such",
    "just", "also", "too", "very", "really", "quite", "rather",
    "of", "in", "to", "for", "with", "on", "at", "from", "by", "about",
    "into", "through", "during", "before", "after", "above", "below",
    "between", "under", "again", "further", "once", "here", "there",
    "up", "down", "out", "off", "over", "under", "more", "most",
    "other", "another", "even", "still", "already", "always", "never",
    "sometimes", "often", "usually", "generally", "commonly",
})

MAX_INTENT_CHARS = 5000


class InvalidProposalIntent(ValueError):
    """Raised when natural-language proposal text is empty or not meaningful."""


__all__ = [
    "InvalidProposalIntent",
    "MAX_INTENT_CHARS",
    "ACTION_VERBS",
    "TARGET_NOUNS",
    "MODIFIER_PREPOSITIONS",
    "COMPONENT_SPLITTERS",
    "STOP_WORDS",
]
